### ISSUE TITLE
debian9/ubuntu18安装报错

### ISSUE THREAD

**Issue by BrunuhVille** [ukuq/onepoint#15]
npm和pm2安装正常，输入npm，pm2有反应
 cd onepoint-master/
npm install
(>前加了括号()，不加括号的话>会自动显示成竖线)
()  > fast-xml-parser@3.16.0 postinstall /root/onepoint-master/node_modules/fast-xml-parser
()  > node tasks/postinstall.js || exit 0

internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module '/root/onepoint-master/node_modules/fast-xml-parser/tasks/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
added 8 packages from 16 contributors and audited 8 packages in 0.741s
found 0 vulnerabilities

debian9/ ubuntu18都是这样

**Comment by BrunuhVille** [comment]
群内大佬指点，已解决
